name: Copy to GCS

on:
  push:
    branches:
      - main

jobs:
  copy_to_gcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Include any dependencies your script needs

      - name: Run Python script
        run: python main.py

      - name: Set up Google Cloud SDK
        run: |
          echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} | base64 --decode > /tmp/keyfile.json
          gcloud auth activate-service-account --key-file=/tmp/keyfile.json

      - name: Upload to GCS
        run: |
          gsutil cp model3_notebook.json gs://aureus-bucket/githubTest/
